// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	imap "github.com/vdavid/vmail/backend/internal/imap"

	models "github.com/vdavid/vmail/backend/internal/models"

	websocket "github.com/vdavid/vmail/backend/internal/websocket"
)

// IMAPService is an autogenerated mock type for the IMAPService type
type IMAPService struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *IMAPService) Close() {
	_m.Called()
}

// Search provides a mock function with given fields: ctx, userID, query, page, limit
func (_m *IMAPService) Search(ctx context.Context, userID string, query string, page int, limit int) ([]*models.Thread, int, error) {
	ret := _m.Called(ctx, userID, query, page, limit)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*models.Thread
	var r1 int
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) ([]*models.Thread, int, error)); ok {
		return rf(ctx, userID, query, page, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, int) []*models.Thread); ok {
		r0 = rf(ctx, userID, query, page, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*models.Thread)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int, int) int); ok {
		r1 = rf(ctx, userID, query, page, limit)
	} else {
		r1 = ret.Get(1).(int)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string, int, int) error); ok {
		r2 = rf(ctx, userID, query, page, limit)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ShouldSyncFolder provides a mock function with given fields: ctx, userID, folderName
func (_m *IMAPService) ShouldSyncFolder(ctx context.Context, userID string, folderName string) (bool, error) {
	ret := _m.Called(ctx, userID, folderName)

	if len(ret) == 0 {
		panic("no return value specified for ShouldSyncFolder")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return rf(ctx, userID, folderName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = rf(ctx, userID, folderName)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, userID, folderName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StartIdleListener provides a mock function with given fields: ctx, userID, hub
func (_m *IMAPService) StartIdleListener(ctx context.Context, userID string, hub *websocket.Hub) {
	_m.Called(ctx, userID, hub)
}

// SyncFullMessage provides a mock function with given fields: ctx, userID, folderName, imapUID
func (_m *IMAPService) SyncFullMessage(ctx context.Context, userID string, folderName string, imapUID int64) error {
	ret := _m.Called(ctx, userID, folderName, imapUID)

	if len(ret) == 0 {
		panic("no return value specified for SyncFullMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) error); ok {
		r0 = rf(ctx, userID, folderName, imapUID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SyncFullMessages provides a mock function with given fields: ctx, userID, messages
func (_m *IMAPService) SyncFullMessages(ctx context.Context, userID string, messages []imap.MessageToSync) error {
	ret := _m.Called(ctx, userID, messages)

	if len(ret) == 0 {
		panic("no return value specified for SyncFullMessages")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []imap.MessageToSync) error); ok {
		r0 = rf(ctx, userID, messages)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SyncThreadsForFolder provides a mock function with given fields: ctx, userID, folderName
func (_m *IMAPService) SyncThreadsForFolder(ctx context.Context, userID string, folderName string) error {
	ret := _m.Called(ctx, userID, folderName)

	if len(ret) == 0 {
		panic("no return value specified for SyncThreadsForFolder")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, folderName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIMAPService creates a new instance of IMAPService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMAPService(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMAPService {
	mock := &IMAPService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
