// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	imap "github.com/vdavid/vmail/backend/internal/imap"
)

// IMAPPool is an autogenerated mock type for the IMAPPool type
type IMAPPool struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *IMAPPool) Close() {
	_m.Called()
}

// GetListenerConnection provides a mock function with given fields: userID, server, username, password
func (_m *IMAPPool) GetListenerConnection(userID string, server string, username string, password string) (imap.ListenerClient, error) {
	ret := _m.Called(userID, server, username, password)

	if len(ret) == 0 {
		panic("no return value specified for GetListenerConnection")
	}

	var r0 imap.ListenerClient
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, string, string) (imap.ListenerClient, error)); ok {
		return rf(userID, server, username, password)
	}
	if rf, ok := ret.Get(0).(func(string, string, string, string) imap.ListenerClient); ok {
		r0 = rf(userID, server, username, password)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(imap.ListenerClient)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string, string, string) error); ok {
		r1 = rf(userID, server, username, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RemoveClient provides a mock function with given fields: userID
func (_m *IMAPPool) RemoveClient(userID string) {
	_m.Called(userID)
}

// RemoveListenerConnection provides a mock function with given fields: userID
func (_m *IMAPPool) RemoveListenerConnection(userID string) {
	_m.Called(userID)
}

// WithClient provides a mock function with given fields: userID, server, username, password, fn
func (_m *IMAPPool) WithClient(userID string, server string, username string, password string, fn func(imap.IMAPClient) error) error {
	ret := _m.Called(userID, server, username, password, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithClient")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, string, func(imap.IMAPClient) error) error); ok {
		r0 = rf(userID, server, username, password, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewIMAPPool creates a new instance of IMAPPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewIMAPPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *IMAPPool {
	mock := &IMAPPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
