// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	client "github.com/emersion/go-imap/client"

	mock "github.com/stretchr/testify/mock"
)

// ListenerClient is an autogenerated mock type for the ListenerClient type
type ListenerClient struct {
	mock.Mock
}

// GetClient provides a mock function with no fields
func (_m *ListenerClient) GetClient() *client.Client {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 *client.Client
	if rf, ok := ret.Get(0).(func() *client.Client); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Client)
		}
	}

	return r0
}

// Lock provides a mock function with no fields
func (_m *ListenerClient) Lock() {
	_m.Called()
}

// Unlock provides a mock function with no fields
func (_m *ListenerClient) Unlock() {
	_m.Called()
}

// NewListenerClient creates a new instance of ListenerClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewListenerClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *ListenerClient {
	mock := &ListenerClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
