// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ThreadCountUpdater is an autogenerated mock type for the ThreadCountUpdater type
type ThreadCountUpdater struct {
	mock.Mock
}

// UpdateThreadCount provides a mock function with given fields: ctx, userID, folderName
func (_m *ThreadCountUpdater) UpdateThreadCount(ctx context.Context, userID string, folderName string) error {
	ret := _m.Called(ctx, userID, folderName)

	if len(ret) == 0 {
		panic("no return value specified for UpdateThreadCount")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, userID, folderName)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewThreadCountUpdater creates a new instance of ThreadCountUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewThreadCountUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *ThreadCountUpdater {
	mock := &ThreadCountUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
